name: kotest-github-actions
run-name: ${{ github.actor }} is Kotest GitHub Actions
on: [push]
jobs:
  build:
    # <!-- This is a YAML comment for use in annotated code examples. -->
    runs-on: ubuntu-latest
    #
    steps:
      # このステップでは、`actions/checkout` アクションで、ランナーにリポジトリのコピーをダウンロードします。
      - uses: actions/checkout@v4
      # このステップでは、`actions/setup-java` アクションで、Eclipse Adoptium による Eclipse Temurin (Java) 17 JDK を構成します。
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      # The "Validate Gradle wrapper" step validates the checksums of Gradle Wrapper JAR files present in the source tree.
      - name: Java version check
        run: java -version